<a href="https://colab.research.google.com/github/monta0315/pytorch_pra/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# テンソル:Tensors
=======================

テンソルは特殊なデータ構造で、配列や行列によく似ている

PyTorchではテンソル型の変数を使用して、モデルの入出力、パラメータを表現する

テンソルはNumpyのndarraysに似ているが、違いとしてGPUや他のハードウェアアクセラレータ状でどうさせることができる

テンソルとNumpyの配列は基本的には同じメモリを共有することができるため、2つの型間での変換時にはデータをコピーする必要がない！！

テンソルはその他に、自動微分に最適化されている


In [ ]:
%matplotlib inline

In [ ]:
import torch
import numpy as np

#テンソルの初期化

テンソルは様々な手法で初期化できる

**データから直接テンソルに変換**


In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)
print(data)

tensor([[1, 2],
        [3, 4]])
[[1, 2], [3, 4]]


#NumpyとTensorは相互に変換可能

In [ ]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


#他のテンソルから作成
明示的に上書きされない限り、引数のテンソルのプロパティを保持する

In [ ]:
x_ones = torch.ones_like(x_data)
print(x_ones) #2x2は引き継がれている
x_rand = torch.rand_like(x_data,dtype=torch.float) #x_dataのdatatypeを上書き
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.3701, 0.6303],
        [0.7334, 0.8679]])


#ランダム値や定数のテンソルの作成
shapeはテンソルの次元を表すタプル
以下の例ではshapeからのテンソルのサイズを決めている

In [ ]:
shape=(2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.4020, 0.1826, 0.0856],
        [0.8871, 0.0369, 0.6982]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#テンソルの属性変数
テンソルは属性変数として、その形状、データの型、保存されているデバイスを保持している

In [ ]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


#テンソルの操作
デフォルトではテンソルはCPU上に作成される
そのため、明示的に.toメソッドを使用してテンソルをGPU上に移動させる

In [15]:
#GPUが使用可能であったらGPU上にテンソルを移動させる
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [17]:
tensor = torch.ones(4,4)
print(tensor)
print(tensor[0]) #first low
print(tensor[:,0]) #first column
print(tensor[...,-1]) # last column
tensor[:,1]=0 #change second column 
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#テンソルの結合
torch.catを使用することでテンソルを特定の次元に沿って結合することができる

torch.catと似たような動きをするtorch.stackもある

In [23]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


#算術演算

In [30]:
#2つのテンソル行列の掛け算　y1,y2,y3は等価
print(tensor)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
print(y3.T)
torch.matmul(tensor,tensor.T,out=y3)
print(y1)
print(y2)
print(y3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[0.9253, 0.0624, 0.0448, 0.8034],
        [0.9446, 0.0192, 0.7633, 0.1834],
        [0.4339, 0.8179, 0.1067, 0.8001],
        [0.1973, 0.0369, 0.9879, 0.1686]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [33]:
#要素ごとの積を求める
z1 = tensor*tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor.T,out=z3)
print(z1)
print(z2)
print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#1要素のテンソル
テンソルの全要素の足し算などすると生まれる
扱う場合には.item()を使用する

In [35]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item,type(agg_item))

tensor(12.)
12.0 <class 'float'>


#インプレース操作
演算結果をオペランドに格納する演算をインプレースという
メソッドの最後、接尾辞として操作名に_がつく
x.copy_(x),x.t_()などであり、xの内容そのものを変更する

インプレース操作はメモリを節約できるが、演算履歴が失われてしまうため、微分では問題となる

In [36]:
print(tensor,'\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


#Numpyとの変換

In [37]:
#TensorTO Numpy Array
t = torch.zeros(5)
print(t)
n = t.numpy()
print(n)

tensor([0., 0., 0., 0., 0.])
[0. 0. 0. 0. 0.]


In [38]:
#この際Tensor側が変化するとnumpyも変化する
#これはCPU上ではtensorとnumpyのメモリが共有されているからである
t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [39]:
#numpy側の変化もtensorに反映される
n = np.ones(5)
t = torch.from_numpy(n)
print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
